[project]
name = "ray-gemini-batch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-aiplatform>=1.140.0",
    "google-cloud-bigquery>=3.40.1",
    "google-cloud-bigquery-storage>=2.36.2",
    "google-cloud-storage>=3.9.0",
    "google-genai>=1.66.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.2",
    "ray[data,default]>=2.54.0",
]
